#!/bin/sh


# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
sleep 1
/System/Services/Services.sh stop
echo "[Init Stage 1 Shutting down...]"
for i in $(ls -r /etc/init.d/S??*) ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i stop
	    ;;
    esac
done

